use learningmysql;
create database learningmysql;
desc new_table;
create table shirts (name varchar(30),size enum('xsmall','small','medium','large'));
insert into shirts values('POLO','small');
insert into shirts values('corcs','large');
insert into shirts values('JP','large');
create table books (Book_No INT,Book_name varchar(30),Author_name varchar(30),Cost INT,Category char(10));
insert into books(Book_No,Book_name,Author_name,Cost,Category) values('101','Let us C',	'Denis Ritchie',450,'System'),('102','Oracle – Complete Ref','Loni','550','Database'),('103','Mastering SQL','Loni',	'250',	'Database'),
('104','PL SQL-Ref','Scott Urman','750','Database');
desc books;
select * from books;
select * from books_ where Book_name LIKE 'O%';
drop table books;
SET SQL_SAFE_UPDATES=0;
update books set Cost=Cost+150;
select Book_name from books where Category =  'Database';
select Book_name,cost from books where Category = 'Database' OR 'System';
alter table books add column published_year int;
update books set published_year=1995 ;
alter table books add column Suscribers int;
update books set Suscribers=20 ;
alter table books modify Author_name varchar(255);
alter table book rename to BOOKS;
select * from books where Cost <(select avg(cost) from books );
drop database Pustak;
select * into Pustak from books;
create table books_temp2 as select * from books where 'A'='B';
select * from books where cost=(select max(cost)from books);
select Author_name from books group by Author_name having count(distinct Book_name)>1;